FROM apache/spark:3.5.1

USER root

RUN pip3 install --no-cache-dir \
    pytest==8.3.3 \
    pyyaml==6.0.2 \
    pyarrow==17.0.0 \
    pandas==2.0.3

ENV PYTHONPATH="/opt/spark/python:/opt/spark/python/lib/py4j-0.10.9.7-src.zip:${PYTHONPATH}"

WORKDIR /opt/smart-drive
